const express = require('express');
const pdf = require('html-pdf');
const router = express.Router();

router.get('/', (req, res) => {
    const html = `
        <html>
            <body>
                <h1>Exported PDF</h1>
                <p>This is a sample PDF generated by the API.</p>
            </body>
        </html>
    `;

    pdf.create(html).toBuffer((err, buffer) => {
        if (err) {
            res.status(500).send('Error generating PDF');
        } else {
            res.set('Content-Type', 'application/pdf');
            res.send(buffer);
        }
    });
});

module.exports = router;
